name: stack_attack
description: Prettify your stack traces in Dart command line interfaces
version: 0.0.1
repository: https://github.com/shyndman/stack_attack

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  io: ^1.0.0
  path: ^1.8.0
  quiver: ^3.0.0
  stack_trace: ^1.10.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
